### ISSUE TITLE
Valhalla API yields GraphTile DirectedEdge index out of bounds

### ISSUE THREAD

**Issue by danvk** [valhalla/baldr#236] opened 2016-03-29 16:36 UTC
I ran into an error using the Valhalla API which seems to be coming from this repo:

```
$ curl -D - 'https://valhalla.mapzen.com/route?api_key=valhalla-....&json=%7B%22costing%22%3A+%22auto%22%2C+%22locations%22%3A+%5B%7B%22lat%22%3A+37.938641883140285%2C+%22lon%22%3A+-122.05604945405771%7D%2C+%7B%22lat%22%3A+38.017348857116026%2C+%22lon%22%3A+-122.15886008984188%7D%5D%7D'

HTTP/1.1 400 Bad Request
access-control-allow-origin: *
Date: Tue, 29 Mar 2016 16:28:37 GMT
Server: nginx/1.4.6 (Ubuntu)
X-ApiaxleProxy-Qpd-Left: 48853
X-ApiaxleProxy-Qps-Left: 1
Content-Length: 84
Connection: keep-alive

GraphTile DirectedEdge index out of bounds: 45777,1,185080 directededgecount= 185080%
```

Here's the decoded request:

```
{
  "costing": "auto",
  "locations": [
    {"lat": 37.938641883140285, "lon": -122.05604945405771},
    {"lat": 38.017348857116026, "lon": -122.15886008984188}
  ]
}
```

I think the issue is that the end location is inside a park. But then the error should be `No path could be found`, rather than `GraphTile DirectedEdge index out of bounds`.

(Feel free to suggest that I refile somewhere else.)

**Comment by kevinkreiser** [comment] 2016-03-29 17:18
Taking a look, thanks for reporting!

**Comment by kevinkreiser** [comment] 2016-03-29 18:28
@dnesbitt61 found this: 

https://github.com/valhalla/thor/blob/master/src/thor/trippathbuilder.cc#L969

'AddTripIntersectingEdge' which will look at the edges at a node to check for walk/cyclablility. the problem is that we dont have all the edges if we are on any level of the hierarchy but the local one. so this code will currently read in the wrong edges to look for walk/cyclablility or indeed read passed the end of them!

the good news is, they are only useful when routing with modes that stay on the local level so we can just check before we go to do this, that we are asking for this information on the local level. ps heres where its used (`EnhancedTripPath_IntersectingEdge::IsTraversableOutbound`):

https://github.com/valhalla/odin/blob/master/src/odin/enhancedtrippath.cc#L636

**Comment by dnesbitt61** [comment] 2016-03-30 15:11
This should now be fixed in production. Thanks for reporting this issue.

**Closed by dnesbitt61** 2016-03-30 15:11 UTC
